import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Navbar } from "@/components/navbar";
import { Providers } from "@/components/providers";

import localFont from "next/font/local";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const myFont1 = localFont({
	src: "../../public/fonts/Geist-Regular.ttf",
	
});

const myFont2 = localFont({
  src: "../../public/fonts/Roboto-VariableFont.ttf",
});


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`antialiased ${myFont2}`}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
